dist: xenial
language: node_js
node_js:
  - 8
  - 10
  - 12
  - node

matrix:
  include:
    - name: Lint
      node_js: 12
      script: npm run lint

sudo: 'required'
before_install: 'sudo apt-get update && sudo apt-get install -y graphicsmagick'
script: npm run test:ci
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
