dist: xenial
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
sudo: 'required'
before_install: 'sudo apt-get update && sudo apt-get install -y graphicsmagick'
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
script: 'npm run ci'
